import os
from dotenv import load_dotenv

load_dotenv()

# OAuth App
GITHUB_CLIENT_ID = os.getenv("GITHUB_CLIENT_ID")
print(f"GITHUB_CLIENT_ID:{GITHUB_CLIENT_ID}")
GITHUB_CLIENT_SECRET = os.getenv("GITHUB_CLIENT_SECRET")
print(f"GITHUB_CLIENT_SECRET:{GITHUB_CLIENT_SECRET}")

# GitHub App
GITHUB_APP_ID = os.getenv("GITHUB_APP_ID")
print(f"GITHUB_APP_ID:{GITHUB_APP_ID}")
GITHUB_APP_CLIENT_ID = os.getenv("GITHUB_APP_CLIENT_ID")
print(f"GITHUB_APP_CLIENT_ID:{GITHUB_APP_CLIENT_ID}")
GITHUB_APP_CLIENT_SECRET = os.getenv("GITHUB_APP_CLIENT_SECRET")
print(f"GITHUB_APP_CLIENT_SECRET:{GITHUB_APP_CLIENT_SECRET}")
GITHUB_PRIVATE_KEY_PATH = os.getenv("GITHUB_PRIVATE_KEY_PATH")
print(f"GITHUB_PRIVATE_KEY_PATH:{GITHUB_PRIVATE_KEY_PATH}")

# LLM
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
VERTEX_AI_API_KEY = os.getenv("VERTEX_AI_API_KEY")

# JOB ENV
GCP_PROJECT_ID = os.getenv("GCP_PROJECT_ID")
GCP_REGION = os.getenv("GCP_REGION")
CLOUD_RUN_JOB = os.getenv("CLOUD_RUN_JOB")

# FrontEnd URL
FRONTEND_URL = os.getenv("FRONTEND_URL")
print(f"frontend url:{FRONTEND_URL}")

# Backend URL
BACKEND_URL = os.getenv("BACKEND_URL")

